apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - port: 80               # Service port
      targetPort: 80         # Container port
      nodePort: 30080        # NodePort (must be between 30000–32767)
